---
alertmanager_cluster_peers:
  us-east-2a:
    - alertmanager-2b.{{ hosted_zone_name }}:{{ alertmanager_cluster_tcp_port }}
    - alertmanager-2c.{{ hosted_zone_name }}:{{ alertmanager_cluster_tcp_port }}
  us-east-2b:
    - alertmanager-2a.{{ hosted_zone_name }}:{{ alertmanager_cluster_tcp_port }}
    - alertmanager-2c.{{ hosted_zone_name }}:{{ alertmanager_cluster_tcp_port }}
  us-east-2c:
    - alertmanager-2a.{{ hosted_zone_name }}:{{ alertmanager_cluster_tcp_port }}
    - alertmanager-2b.{{ hosted_zone_name }}:{{ alertmanager_cluster_tcp_port }}
alertmanager_tcp_port: 9093
alertmanager_cluster_tcp_port: 9094
alertmanager_version: 0.30.0
alertmanager_config_vigil_alert_triage_url: "https://vigil.{{ hosted_zone_name }}/api/v1/alerts"
