---
  ebpf_exporter_tcp_port: 9435
  ebpf_exporter_flags: >
    --config.dir={{ ebpf_exporter_base_directory }}/modules
    --config.names=biolatency,ext4dist,oomkill,percpu-softirq,softirq-latency,syscalls,tcp-retransmit,tcp-syn-backlog,tcp-window-clamps,udp-drops,unix-socket-backlog
  prometheus_node_exporter_tcp_port: 9100
  prometheus_system_user: prometheus
  prometheus_node_exporter_flags: >
    --no-collector.bonding
    --no-collector.conntrack
    --no-collector.fibrechannel
    --no-collector.infiniband
    --no-collector.ipvs
    --no-collector.tapestats
    --no-collector.zfs
    --collector.ethtool
    --collector.logind
    --collector.mountstats
    --collector.processes
    --collector.tcpstat
    --collector.textfile.directory="/home/{{ prometheus_system_user }}/scrapedata"
    --collector.diskstats.device-exclude="^(z?ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\\d+n\\d+p)\\d+$"
    --collector.filesystem.mount-points-exclude="^/(dev|proc|run/credentials/.+|run/.+|sys|var/lib/docker/.+|var/lib/containers/storage/.+)($|/)"
    --collector.filesystem.fs-types-exclude="^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|tmpfs)$"
    --collector.ethtool.device-exclude="^(veth|docker).*"
    --log.format=json
