---
prometheus_config:

  scrape:
    apps:
      - alertmanager
      - grafana
      - loki
      - mimir
      - prometheus
      - pyroscope
      - tempo
      - vigil
    blackbox:
      - blackbox-http
    blackbox_http:
      - alertmanager
      - grafana
      - loki
      - mimir
      - pyroscope
      - tempo
    node:
      - node-exporter
      - ebpf-exporter

  rules:
    recording:
      - apps/loki-rules
      - apps/mimir-rules
      - apps/pyroscope-rules
      - apps/tempo-rules
    alerting:
      - node/cpu
      - node/disk
      - node/mem
      - node/net
      - node/os
      - node/time
      - node/up
      - apps/grafana-alerts
      - apps/alertmanager-alerts
      - apps/loki-alerts
      - apps/mimir-alerts
      - apps/prometheus-alerts
      - apps/tempo-alerts
