prometheus:

  scrape:
    apps:
      - alertmanager
      - loki
      - mimir
      - prometheus
      - pyroscope
      - tempo
    blackbox:
      - blackbox-http
    blackbox_http:
      - alertmanager
      - grafana
      - loki
      - mimir
      - pyroscope
      - tempo
    infra:
      - aws-sd-infra
      - aws-sd-ebpf

  rules:
    recording:
      - node/cpu
      - node/disk
      - node/mem
      - node/net
      - node/os
      - node/time
      - node/up
      - apps/loki-rules
      - apps/mimir-rules
      - apps/pyroscope-rules
      - apps/tempo-rules
    alerting:
      - apps/alertmanager-alerts
      - apps/loki-alerts
      - apps/mimir-alerts
      - apps/prometheus-alerts
      - apps/tempo-alerts
