---
prometheus_config:

  scrape:
    apps:
      - prometheus
      - sitesuper
    node:
      - node-exporter
      - ebpf-exporter

  rules:
    alerting:
      - apps/prometheus-alerts
      - node/cpu
      - node/disk
      - node/mem
      - node/net
      - node/os
      - node/time
      - node/up
