---
rekor_version: 2.2.1
rekor_binary_sha256: b7f7bf59b5841e1bb14a527a2936def6332c43a4dd17f6a34c009a52cf01fe7b

rekor_hostname: rekor.trust.linnemanlabs.com
rekor_db_type: rds
rekor_db_name: rekor
rekor_server_http_address: 0.0.0.0
rekor_server_http_port: 3000
rekor_server_http_tls_enabled: false
rekor_server_grpc_address: 127.0.0.1
rekor_server_grpc_port: 3001
rekor_server_grpc_tls_enabled: false
rekor_server_metrics_port: 2112
rekor_kms_signer_param: "arn:aws:ssm:us-east-2:987020212918:parameter/app/rekor/signing/checkpoint/signer"
rekor_kms_hash_algorithm: sha256
rekor_log_level: info
