---
- name: Include OS variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

- name: Get instance metadata
  amazon.aws.ec2_metadata_facts:

- name: Set facts from ssm here since they require ec2 metadata to lookup region
  ansible.builtin.set_fact:
    account_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/account/name', region=ansible_ec2_instance_identity_document_region) }}"
    artifacts_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/artifacts/bucket/name', region=ansible_ec2_instance_identity_document_region) }}"
    company_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/company/name', region=ansible_ec2_instance_identity_document_region) }}"
    env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region) }}"
    hosted_zone_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/dns/hosted_zone/name', region=ansible_ec2_instance_identity_document_region) }}"
    platform_env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region) }}"
    alerts_push_endpoints: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/alerts/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    metrics_push_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/metrics/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    traces_push_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/traces/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    pyroscope_s3_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/app/pyroscope/s3/bucket/name', region=ansible_ec2_instance_identity_document_region) }}"

- name: Set facts from environment variables
  ansible.builtin.set_fact:
    service_name: "{{ ansible_env.SERVICENAME | default('unknown') }}"
    service_component: "{{ ansible_env.SERVICECOMPONENT | default(ansible_env.SERVICENAME | default('unknown')) }}"
    project: "{{ ansible_env.PROJECT | default('unknown') }}"
    service_namespace: "{{ ansible_env.NAMESPACE | default('unknown') }}"
    pyroscope_role: "{{ lookup('env', 'PYROSCOPEROLE') }}"

- name: Print all environment vars for debugging
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 2

- name: Exit with failure if no pyroscope role is defined
  ansible.builtin.fail:
    msg: No ansible roles found in ENV var PYROSCOPEROLE (expected one of 'distributor', 'ingester', 'query-frontend', 'querier', 'query-scheduler',
      'store-gateway', 'compactor')
  when: pyroscope_role not in ['distributor', 'ingester', 'query-frontend', 'querier', 'query-scheduler', 'store-gateway', 'compactor']

- name: Ensure required variables are defined
  ansible.builtin.fail:
    msg: "{{ item }} must be defined use -e {{ item }}=value"
  when: (lookup('vars', item, default=None)) is none
  loop:
    - env
    - pyroscope_role

- name: Create pyroscope user
  ansible.builtin.user:
    name: "{{ pyroscope_system_user }}"
    password: "*"
    umask: "027"
    shell: /usr/sbin/nologin
    system: true

- name: Create pyroscope bin, conf, data directories
  ansible.builtin.file:
    path: /home/{{ pyroscope_system_user }}/{{ item }}
    owner: "{{ pyroscope_system_user }}"
    group: "{{ pyroscope_system_user }}"
    mode: "0750"
    state: directory
  loop:
    - bin
    - conf
    - conf/ssl
    - data

- name: Check if ssl cert already exists
  ansible.builtin.stat:
    path: /home/{{ pyroscope_system_user }}/conf/ssl/cert.pem
  register: pyroscope_cert

- name: Generate private key for local self signed ssl cert
  community.crypto.openssl_privatekey:
    path: /home/{{ pyroscope_system_user }}/conf/ssl/cert.key
    owner: "{{ pyroscope_system_user }}"
  when: not pyroscope_cert.stat.exists

- name: Generate CSR for self-signed certificate for local https listener
  community.crypto.openssl_csr_pipe:
    privatekey_path: /home/{{ pyroscope_system_user }}/conf/ssl/cert.key
    common_name: "{{ ansible_nodename }}"
  register: csr
  when: not pyroscope_cert.stat.exists

- name: Generate self-signed certificate for local https listener
  community.crypto.x509_certificate:
    path: /home/{{ pyroscope_system_user }}/conf/ssl/cert.pem
    csr_content: "{{ csr.csr }}"
    privatekey_path: /home/{{ pyroscope_system_user }}/conf/ssl/cert.key
    owner: "{{ pyroscope_system_user }}"
    provider: selfsigned
  when: not pyroscope_cert.stat.exists

- name: Check if pyroscope is already installed
  ansible.builtin.stat:
    path: /home/{{ pyroscope_system_user }}/bin/pyroscope
  register: pyroscope_binary

# - name: Get latest pyroscope release info from github
#  uri:
#    url: https://api.github.com/repos/grafana/pyroscope/releases/latest
#    return_content: yes
#  register: pyroscope_release_info

# - name: Set release tag fact
#  set_fact:
#    pyroscope_release_tag: "{{ pyroscope_release_info.json.tag_name }}"

# - name: Fail if pyroscope_release_tag asset not found
#  fail:
#    msg: "No asset found github latest release response"
#  when: pyroscope_release_tag is not defined

# - name: Set filename based on architecture
#  set_fact:
#    pyroscopecollector_asset_url: >-
#      {%- if ansible_architecture == "aarch64" -%}
#      https://github.com/grafana/pyroscope/releases/download/{{ pyroscope_release_tag }}/pyroscope_{{ pyroscope_release_tag[1:] }}_linux_arm64.tar.gz
#      {%- else -%}
#      https://github.com/grafana/pyroscope/releases/download/{{ pyroscope_release_tag }}/pyroscope_{{ pyroscope_release_tag[1:] }}_linux_amd64.tar.gz
#      {%- endif -%}

# - name: Download the latest pyroscope release from github
#  get_url:
#    url: "{{ pyroscopecollector_asset_url }}"
#    dest: /home/{{ pyroscope_system_user }}/pyroscope.tar.gz

- name: Set normalized architecture name
  ansible.builtin.set_fact:
    arch_normalized: >-
      {%- if ansible_architecture == "aarch64" -%} arm64{%- else -%} amd64{%- endif -%}

- name: Get pinned pyroscope release from s3 artifacts bucket
  amazon.aws.s3_object:
    bucket: "{{ artifacts_bucket_name }}"
    object: "thirdparty/grafana/pyroscope/v{{ pyroscope_version }}/pyroscope_{{ pyroscope_version }}_linux_{{ arch_normalized }}.tar.gz"
    dest: /home/{{ pyroscope_system_user }}/pyroscope.tar.gz
    mode: get
    overwrite: different

- name: Decompress pyroscope installation package
  ansible.builtin.unarchive:
    src: /home/{{ pyroscope_system_user }}/pyroscope.tar.gz
    dest: /home/{{ pyroscope_system_user }}/bin
    extra_opts: ["--show-stored-names"]
    include: "pyroscope"
    owner: "{{ pyroscope_system_user }}"
    group: "{{ pyroscope_system_user }}"
    mode: "0750"
    creates: /home/{{ pyroscope_system_user }}/bin/pyroscope

- name: Remove the pyroscope package
  ansible.builtin.file:
    path: /home/{{ pyroscope_system_user }}/pyroscope.tar.gz
    state: absent

- name: Create pyroscope systemd service
  ansible.builtin.template:
    src: /etc/systemd/system/pyroscope.service.j2
    dest: /etc/systemd/system/{{ pyroscope_systemd_service_name[pyroscope_role] }}.service
    mode: "0644"

- name: Modify pyroscope main configuration
  ansible.builtin.template:
    src: /pyroscope/conf/pyroscope.yml.j2
    dest: /home/{{ pyroscope_system_user }}/conf/pyroscope.yml
    mode: "0640"
    owner: "{{ pyroscope_system_user }}"
    group: "{{ pyroscope_system_user }}"
  notify: Restart pyroscope service

- name: Run handlers immediately to refresh systemd daemon configuration
  ansible.builtin.meta: flush_handlers
- name: Enable systemd service {{ pyroscope_systemd_service_name[pyroscope_role] }}
  ansible.builtin.service:
    name: "{{ pyroscope_systemd_service_name[pyroscope_role] }}"
    state: started
    enabled: true

- name: Allow pyroscope http traffic through firewall
  community.general.ufw:
    port: "{{ pyroscope_http_tcp_port }}"
    proto: tcp
    rule: allow
  # this is used both for service traffic in case of distributors and query-frontend, and for prometheus metrics scraping on all services
  # when: ansible_distribution == 'Ubuntu' and (pyroscope_role == 'distributor' or pyroscope_role == 'query-frontend')
  when: ansible_distribution == 'Ubuntu'

- name: Allow pyroscope grpc traffic through firewall
  community.general.ufw:
    port: "{{ pyroscope_grpc_tcp_port }}"
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'

- name: Allow pyroscope cluster memberlist tcp traffic through firewall
  community.general.ufw:
    port: "{{ pyroscope_cluster_memberlist_port }}"
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'

- name: Allow pyroscope cluster memberlist udp traffic through firewall
  community.general.ufw:
    port: "{{ pyroscope_cluster_memberlist_port }}"
    proto: udp
    rule: allow
  when: ansible_distribution == 'Ubuntu'
