---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Get instance metadata
  ec2_metadata_facts:

- name: Print all environment vars for debugging
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 2

- name: Ensure required variables are defined
  fail:
    msg: "{{ item }} must be defined use -e {{ item }}=value"
  when: (lookup('vars', item, default=None)) is none
  loop:
    - env

- name: Ensure sshd DisableForwarding is not active (undoes CIS 5.1.8 set in common-security)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^.*DisableForwarding .*'
    line: 'DisableForwarding no'
    #backup: true
    backrefs: false
    create: true
  notify: Restart service sshd
