---
common_remove_package_names:
  #  - snapd
  - fwupd
  - fwupd-signed
  - motd-news-config
  - bluez
  #  - telnet
  - realvnc-vnc-server
  - landscape-client
  - landscape-common

common_install_package_names:
  #  - python3-pip
  #  - awscli
  - lsof
  - nano
  - bind9-dnsutils
  - apparmor-utils
  - jq
  - unzip
  - binutils

common_disable_service_names:
  - accounts-daemon
  - avahi-daemon

common_amazon_ssm_agent_package_filename: amazon-ssm-agent.deb

common_amazon_ssm_agent_package_path:
  aarch64: debian_arm64
  x86_64: debian_amd64

# disabling auto updates by default. can override at playbook runtime
# update frequncy in days. 0 to disable
common_apt_auto_update_interval: 1

# download (but dont apply) updates to the package lists daily at 7:15pm MST - uses systemd timer format
common_apt_update_schedule: "*-*-* 19:15:00 MST"

# install apt security upgrades weekly on Tuesday at 7:15pm MST - uses systemd timer format
common_apt_upgrade_schedule: "Tue *-*-* 19:15:00 MST"

# cant disable snap auto updates conveniently - setting auto updates of snaps to Tues 7:05pm MST (Wed 2am UTC) by default. can override at playbook runtime
common_snap_auto_update_schedule: "wed,02:05"
