---
  loki_tenant_name: "{{ company_name }}"
  tempo_tenant_name: "{{ company_name }}"
  otel_system_user: otel
  otel_collector_configs_baseline: >
    journald
    syslog
  otel_collector_configs_additional:
  otel_collector_feature_gates:
  otel_collector_version: 0.142.0
  otel_collector_tcp_ports:
    scrape: 8888
#    otlp_grpc: 4317
#    otlp_http: 4318
    zpages: 55679
    healthcheck: 13133
