- name: restart oauth2-proxy service
  systemd:
    name: "{{ oauth2proxy_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart prometheus service
  systemd:
    name: "{{ prometheus_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
