- name: restart prometheus service
  systemd:
    name: "{{ prometheus_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart blackbox_exporter service
  systemd:
    name: "{{ blackbox_exporter_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
