---
  hosted_zone_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/dns/hosted_zone/name', region=ansible_ec2_instance_identity_document_region ) }}"
  mimir_cluster_memberlist_port: 7946
  mimir_http_tcp_port: 8443
  mimir_grpc_tcp_port: 9095
  mimir_replication_factor: 3
  mimir_s3_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/app/mimir/s3/bucket/name', region=ansible_ec2_instance_identity_document_region ) }}"
  mimir_version: 2.17.3
  mimir_system_user: mimir
  mimir_systemd_service_name:
    distributor: mimir-distributor
    ingester: mimir-ingester
    query-frontend: mimir-query-frontend
    querier: mimir-querier
    query-scheduler: mimir-query-scheduler
    store-gateway: mimir-store-gateway
    compactor: mimir-compactor
