---
  memcached_exporter_tcp_port: 11212
  memcached_max_memory:
    t4g.micro: 768
    t4g.small: 1536
    m8g.medium: 3072
    t4g.medium: 3072
    c8g.large: 3072
    r8g.medium: 7168
    m8g.large: 7168
    t4g.large: 7168
    c8g.xlarge: 7168
    r8g.large: 14336
    m8g.xlarge: 14336
    c8g.2xlarge: 14336
    r8g.xlarge: 28672
    m8g.2xlarge: 28672
    c8g.4xlarge: 28672
  memcached_tcp_port: 11211
  memcached_exporter_version: 0.15.4