---
- name: Restart service systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
- name: Reload systemd configurations
  ansible.builtin.systemd:
    daemon_reload: "true"
- name: Reload-motd-updates
  ansible.builtin.command: /usr/lib/update-notifier/update-motd-updates-available --force
- name: Restart service chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
