---
  company_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/company/name', region=ansible_ec2_instance_identity_document_region ) }}"
  ebpf_exporter_tcp_port: 9435
  hosted_zone_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/dns/hosted_zone/name', region=ansible_ec2_instance_identity_document_region ) }}"
  oauth2proxy_config_cookie_secret: "{{ lookup('amazon.aws.aws_ssm', '/app/prometheus/oauth2_proxy/cookie_secret', region=ansible_ec2_instance_identity_document_region ) }}"
  oauth2proxy_config_okta_oidc_issuer_url: "{{ lookup('amazon.aws.aws_ssm', '/platform/oidc/okta/issuer_url', region=ansible_ec2_instance_identity_document_region ) }}"
  oauth2proxy_config_okta_client_id: "{{ lookup('amazon.aws.aws_ssm', '/app/prometheus/okta/client_id', region=ansible_ec2_instance_identity_document_region ) }}"
  oauth2proxy_config_okta_client_secret: "{{ lookup('amazon.aws.aws_secret', 'app/prometheus/okta/client_secret', region=ansible_ec2_instance_identity_document_region ) }}"
  oauth2proxy_system_user: oauth2-proxy
  oauth2proxy_tcp_port: 4180
  oauth2_redirect_tcp_port: 9090
  platform_env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region ) }}"
  prometheus_node_exporter_tcp_port: 9100
  prometheus_node_exporter_flags: >
    --collector.ethtool
    --collector.logind
    --collector.mountstats
    --collector.textfile.directory="/home/{{ prometheus_system_user }}/scrapedata"
    --collector.diskstats.device-exclude="^(z?ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\\d+n\\d+p)\\d+$"
    --collector.filesystem.mount-points-exclude="^/(dev|proc|run/credentials/.+|run/.+|sys|var/lib/docker/.+|var/lib/containers/storage/.+)($|/)"
    --collector.filesystem.fs-types-exclude="^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|tmpfs)$"
  prometheus_node_ids:
    us-east-2a: 2a
    us-east-2b: 2b
    us-east-2c: 2c
  prometheus_scrape_interval: 15s
  prometheus_scrape_timeout: 10s
  prometheus_system_user: prometheus
  prometheus_tenant_name: "{{ company_name }}-{{ platform_env }}"
  prometheus_tcp_port: 9090
