---
  company_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/company/name', region=ansible_ec2_instance_identity_document_region ) }}"
  hosted_zone_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/dns/hosted_zone/name', region=ansible_ec2_instance_identity_document_region ) }}"
  platform_env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region ) }}"
  blackbox_exporter_version: 0.27.0
  ebpf_exporter_tcp_port: 9435
  prometheus_node_exporter_tcp_port: 9100
  prometheus_node_ids:
    us-east-2a: 2a
    us-east-2b: 2b
    us-east-2c: 2c
  prometheus_scrape_interval: 15s
  prometheus_scrape_timeout: 10s
  prometheus_system_user: prometheus
  prometheus_tenant_name: "{{ company_name }}-{{ platform_env }}"
  prometheus_tcp_port: 9090
