---
common_cosign_version:
  arm64: "3.0.3"

common_cosign_sha256:
  arm64: "81398231362031e3c7afd6a7508c57049460cd7e02736f1ebe89a452102253e5"

common_swap_file_enabled: true
common_swap_file_path: /swapfile
common_swap_file_size: 2G

common_timezone: America/New_York
