---
common_cosign_version:
  arm64: "3.0.5"

common_cosign_sha256:
  arm64: "d098f3168ae4b3aa70b4ca78947329b953272b487727d1722cb3cb098a1a20ab"

common_swap_file_enabled: true
common_swap_file_path: /swapfile
common_swap_file_size: 2G

common_timezone: America/New_York
