---
 - name: grafana playbook
   hosts: all
   become: true
   vars_files:
     - ../vars/default.yml
     - ../vars/{{ ansible_os_family }}.yml

   tasks:
     - name: Get instance metadata
       ec2_metadata_facts:

     - name: Print all environment vars for debugging
       debug:
         var: hostvars[inventory_hostname]
         verbosity: 2

     - name: Ensure required variables are defined
       fail:
         msg: "{{ item }} must be defined use -e {{ item }}=value"
       when: (lookup('vars', item, default=None)) is none
       with_items:
         - env

     - name: Install dependency packages
       package:
         name: "{{ item }}"
         state: present
       with_items:
         - apt-transport-https
         - software-properties-common
         - wget

     - name: Install the grafana gpg key
       shell:
         cmd: wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /usr/share/keyrings/grafana-archive-keyring.gpg
         creates: /usr/share/keyrings/grafana-archive-keyring.gpg

     - name: Ensure grafana gpg key is 644 not 640 or apt breaks
       file:
         path: /usr/share/keyrings/grafana-archive-keyring.gpg
         mode: 0644
         owner: root
         group: root

     - name: Add the grafana apt repository
       apt_repository:
         repo: 'deb [signed-by=/usr/share/keyrings/grafana-archive-keyring.gpg] https://apt.grafana.com stable main'
         state: present
         filename: grafana
         update_cache: true

     - name: Install grafana package
       package:
         name: grafana
         state: present

     - name: Create grafana ssl directory
       file:
         path: /etc/grafana/ssl
         owner: root
         group: "{{ loki_system_user }}"
         mode: 0750
         state: directory

     - name: Generate private key for local self signed ssl cert
       community.crypto.openssl_privatekey:
         path: /etc/grafana/ssl/cert.key
         owner: root
         group: "{{ grafana_system_user }}"
         mode: 0640

     - name: Generate CSR for self-signed certificate for local https listener
       community.crypto.openssl_csr_pipe:
         privatekey_path: /etc/grafana/ssl/cert.key
         common_name: "{{ ansible_nodename }}"
       register: csr

     - name: Generate self-signed certificate for local https listener
       community.crypto.x509_certificate:
         path: /etc/grafana/ssl/cert.pem
         csr_content: "{{ csr.csr }}"
         mode: 0644
         owner: root
         group: "{{ grafana_system_user }}"
         privatekey_path: /etc/grafana/ssl/cert.key
         provider: selfsigned

     - name: Modify grafana main configuration
       template:
         src: ../templates/etc/grafana/grafana.ini.j2
         dest: /etc/grafana/grafana.ini
         mode: 0644
         owner: root
         group: grafana
       notify: restart grafana service
       when: ansible_os_family == 'Debian'

     #- name: Configure grafana for prometheus data source
     #  template:
     #    src: ../templates/etc/grafana/provisioning/datasources/prometheus.yaml.j2
     #    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
     #    mode: 0644
     #    owner: root
     #    group: grafana
     #  notify: restart grafana service
     #  when: ansible_os_family == 'Debian'

     - name: Enable grafana systemd service
       service:
         name: "{{ grafana_systemd_service_name }}"
         state: started
         enabled: true

     - name: Allow grafana traffic through firewall
       ufw:
         port: "{{ grafana_tcp_port }}"
         proto: tcp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

   handlers:
     - name: restart grafana service
       systemd:
         name: "{{ grafana_systemd_service_name }}"
         state: restarted
         enabled: true
         daemon_reload: true
