---
  loki_cluster_memberlist_tcp_port: 7946
  loki_cluster_memberlist_udp_port: 7946
  loki_grpc_tcp_port: 9095
  loki_http_tcp_port: 8443
  loki_replication_factor: 3
  loki_system_user: loki
  loki_systemd_service_name:
    compactor: loki-compactor
    distributor: loki-distributor
    ingester: loki-ingester
    query-frontend: loki-query-frontend
    querier: loki-querier
    query-scheduler: loki-query-scheduler
    ruler: loki-ruler
    index-gateway: loki-index-gateway
  loki_version: 3.5.8
