---
- name: Include OS variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

- name: Get instance metadata
  amazon.aws.ec2_metadata_facts:

- name: Set variable for hostname without instanceid used to correlate metric, logs, traces, profiles, etc
  ansible.builtin.set_fact:
    hostname_no_instanceid: "{{ ansible_hostname.split('-')[0:-1] | join('-') }}"

- name: Set facts from ssm here since they require ec2 metadata to lookup region
  ansible.builtin.set_fact:
    account_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/account/name', region=ansible_ec2_instance_identity_document_region) }}"
    artifacts_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/artifacts/bucket/name', region=ansible_ec2_instance_identity_document_region) }}"
    company_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/company/name', region=ansible_ec2_instance_identity_document_region) }}"
    env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region) }}"
    hosted_zone_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/dns/hosted_zone/name', region=ansible_ec2_instance_identity_document_region) }}"
    platform_env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region) }}"
    alerts_push_endpoints: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/alerts/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    metrics_push_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/metrics/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    traces_push_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/traces/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    profiles_push_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/profiles/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    logs_push_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/logs/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"

- name: Set facts from environment variables
  ansible.builtin.set_fact:
    service_name: "{{ ansible_env.SERVICENAME | default('unknown') }}"
    service_component: "{{ ansible_env.SERVICECOMPONENT | default(ansible_env.SERVICENAME | default('unknown')) }}"
    project: "{{ ansible_env.PROJECT | default('unknown') }}"
    namespace: "{{ ansible_env.NAMESPACE | default('unknown') }}"
    loki_tenant_name: "{{ company_name }}"
    tempo_tenant_name: "{{ company_name }}"

- name: Print all environment vars for debugging
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 2

- name: Ensure required variables are defined
  ansible.builtin.fail:
    msg: "{{ item }} must be defined use -e {{ item }}=value or set the associated ENV var"
  when: vars[item] is not defined or vars[item] is none
  loop:
    - artifacts_bucket_name
    - company_name
    - hosted_zone_name
    - platform_env
    - service_name
    - service_component
    - project
    - namespace
    - hostname_no_instanceid

- name: Create otel user
  ansible.builtin.user:
    name: "{{ otel_system_user }}"
    password: "*"
    umask: "027"
    shell: /usr/sbin/nologin
    system: true

- name: Create otel directories
  ansible.builtin.file:
    path: /home/{{ otel_system_user }}/{{ item }}
    owner: "{{ otel_system_user }}"
    group: "{{ otel_system_user }}"
    mode: "0750"
    state: directory
  loop:
    - bin
    - conf
    - conf.d

# moved to tagged release versions to avoid 'latest' frequently being broken for otel-contrib
#- name: Get latest otel_collector release info from github
#  uri:
#    url: https://api.github.com/repos/open-telemetry/opentelemetry-collector-releases/releases/latest
#    return_content: yes
#  register: otel_collector_release_info

#- name: Set release tag fact
#  set_fact:
#    otel_collector_release_tag: "{{ otel_collector_release_info.json.tag_name }}"

#- name: Fail if otel_collector_release_tag asset not found
#  fail:
#    msg: "No asset found github latest release response"
#  when: otel_collector_release_tag is not defined

# 12/25/25 - moving this to artifacts bucket
#- name: Set filename based on architecture
#  set_fact:
#    otelcollector_asset_url: >-
#      {%- if ansible_architecture == "aarch64" -%}
#      https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/{{ otel_collector_release_tag }}/otelcol-contrib_{{ otel_collector_release_tag[1:] }}_linux_arm64.tar.gz
#      {%- else -%}
#      https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/{{ otel_collector_release_tag }}/otelcol-contrib_{{ otel_collector_release_tag[1:] }}_linux_amd64.tar.gz
#      {%- endif -%}

#- name: Download the latest otel_collector release from github
#  get_url:
#    url: "{{ otelcollector_asset_url }}"
#    dest: /home/{{ otel_system_user }}/otel_collector.tar.gz
#  register: download_result
#  retries: 5
#  delay: 10
#  until: download_result is succeeded

- name: Set normalized architecture name
  ansible.builtin.set_fact:
    arch_normalized: >-
      {%- if ansible_architecture == "aarch64" -%} arm64{%- else -%} amd64{%- endif -%}

- name: Get pinned otel_collector release from s3 artifacts bucket
  amazon.aws.s3_object:
    bucket: "{{ artifacts_bucket_name }}"
    object: "thirdparty/open-telemetry/opentelemetry-collector-releases/v{{ otel_collector_version }}/otelcol-contrib_{{ otel_collector_version }}_linux_{{ arch_normalized
      }}.tar.gz"
    dest: /home/{{ otel_system_user }}/otel_collector.tar.gz
    mode: get
    overwrite: different

- name: Decompress otel_collector installation package
  ansible.builtin.unarchive:
    src: /home/{{ otel_system_user }}/otel_collector.tar.gz
    dest: /home/{{ otel_system_user }}/bin
    extra_opts: ["--show-stored-names"]
    include: "otelcol-contrib"
    owner: "{{ otel_system_user }}"
    group: "{{ otel_system_user }}"
    mode: "0750"
    creates: /home/{{ otel_system_user }}/bin/otelcol-contrib

- name: Remove the otel_collector package
  ansible.builtin.file:
    path: /home/{{ otel_system_user }}/otel_collector.tar.gz
    state: absent

- name: Create otel_collector configuration
  ansible.builtin.template:
    src: ../templates/otel/conf/collector.yaml.j2
    dest: /home/{{ otel_system_user }}/conf/collector.yaml
    mode: "0644"
  notify: restart otel_collector service

- name: Create otel_collector systemd service
  ansible.builtin.template:
    src: ../templates/etc/systemd/system/{{ otel_collector_systemd_service_name }}.service.j2
    dest: /etc/systemd/system/{{ otel_collector_systemd_service_name }}.service
    owner: "{{ otel_system_user }}"
    group: "{{ otel_system_user }}"
    mode: "0644"

# let systemd service task do this to avoid daemon-reload warnings
#- name: Enable otel_collector systemd service
#  service:
#    name: "{{ otel_collector_systemd_service_name }}"
#    state: started
#    enabled: true

- name: Allow otel_collector traffic through firewall
  community.general.ufw:
    port: "{{ item.value }}"
    proto: tcp
    rule: allow
  loop: "{{ otel_collector_tcp_ports | dict2items }}"
  when: ansible_distribution == 'Ubuntu'
