-
  hosts: all
  become: true
  vars_files:
    - ../vars/global.yml
  handlers:
    - import_tasks: ../handlers/main.yml

  tasks:
  - name: Include OS variables
    include_vars: "{{ item }}"
    with_first_found:
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"

  - name: Print all variables for debugging
    debug:
      var: hostvars[inventory_hostname]
      verbosity: 1

  - name: Install wireguard package
    package:
     name: wireguard
     state: installed

  - name: Configure sysctl settings to allow forwarding
    template:
      src: ../templates/etc/sysctl.d/999-wireguard.conf.j2
      dest: /etc/sysctl.d/999-wireguard.conf
    notify: Apply sysctl values

  - name: Configure nftables to allow forwarding
    template:
      src: ../templates/etc/nftables.conf.j2
      dest: /etc/nftables.conf
    notify: Reload nftables
