---
  region_short_name:
    us-east-1: use1
    us-east-2: use2
    us-west-1: usw1
    us-west-2: usw2
  blackbox_exporter_version: 0.28.0
  ebpf_exporter_tcp_port: 9435
  local_tsdb_retention_time: 1d
  prometheus_node_exporter_tcp_port: 9100
  prometheus_node_ids:
    us-east-2a: 2a
    us-east-2b: 2b
    us-east-2c: 2c
  prometheus_scrape_interval: 15s
  prometheus_scrape_timeout: 10s
  #prometheus_tenant_name: "{{ company_name }}-{{ platform_env }}"
  prometheus_tenant_name: "{{ company_name }}"
  prometheus_tcp_port: 9090
  prometheus_version: 3.8.1
