---
  artifacts_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/artifacts/bucket/name', region=ansible_ec2_instance_identity_document_region ) }}"
  company_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/company/name', region=ansible_ec2_instance_identity_document_region ) }}"
  hosted_zone_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/dns/hosted_zone/name', region=ansible_ec2_instance_identity_document_region ) }}"
  platform_env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region ) }}"
  sitesuper_web_tcp_port: 8080
  sitesuper_web_system_user: sitesuper
  sitesuper_web_systemd_service_name: sitesuper-web
  #sitesuper_version: 1.0.1
  sitesuper_version: "{{ lookup('amazon.aws.aws_ssm', '/app/sitesuper/web/prod/release/version', region=ansible_ec2_instance_identity_document_region ) }}"
