---
- name: Include OS variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

- name: Get instance metadata
  amazon.aws.ec2_metadata_facts:

- name: Set facts from ssm here since they require ec2 metadata to lookup region
  ansible.builtin.set_fact:
    artifacts_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/artifacts/bucket/name', region=ansible_ec2_instance_identity_document_region) }}"
    platform_env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region) }}"
    # account_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/account/name', region=ansible_ec2_instance_identity_document_region) }}"
    # company_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/company/name', region=ansible_ec2_instance_identity_document_region) }}"
    # hosted_zone_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/dns/hosted_zone/name', region=ansible_ec2_instance_identity_document_region) }}"
    # alerts_push_endpoints: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/alerts/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    # metrics_push_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/metrics/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"

- name: Print all environment vars for debugging
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 2

- name: Ensure required variables are defined
  ansible.builtin.fail:
    msg: "{{ item }} must be defined use -e {{ item }}=value"
  when: (lookup('vars', item, default=None)) is none
  loop:
    - platform_env
    - artifacts_bucket_name

- name: Create prometheus user
  ansible.builtin.user:
    name: "{{ prometheus_system_user }}"
    password: "*"
    umask: "027"
    shell: /usr/sbin/nologin
    system: true

- name: Create prometheus directories
  ansible.builtin.file:
    path: "/home/{{ prometheus_system_user }}/{{ item }}"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_user }}"
    mode: "0750"
    state: directory
  loop:
    - bin
    - scrapedata

# - name: Get latest prometheus node_exporter release info from github
#  uri:
#    url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
#    return_content: yes
#  register: node_exporter_release_info

# - name: Set release tag fact
#  set_fact:
#    node_exporter_release_tag: "{{ node_exporter_release_info.json.tag_name }}"

- name: Set filename based on architecture
  ansible.builtin.set_fact:
    nodeexporter_arch: >-
      {%- if ansible_architecture == "aarch64" -%} linux-arm64{%- else -%} linux-amd64{%- endif -%}

# - name: Find architecture asset URL from release assets
#  set_fact:
#    node_exporter_asset_url: "{{ item.browser_download_url }}"
#  loop: "{{ node_exporter_release_info.json.assets }}"
#  when: "nodeexporter_arch in item.name"

# - name: Fail if {{ nodeexporter_arch }} asset not found
#  fail:
#    msg: "No {{ nodeexporter_arch }} asset found github latest release response."
#  when: node_exporter_asset_url is not defined

# - name: Download the latest node_exporter ({{ node_exporter_release_tag }}) {{ nodeexporter_arch }} release from github ({{ node_exporter_asset_url }})
#  get_url:
#    url: "{{ node_exporter_asset_url }}"
#    dest: /home/{{ prometheus_system_user }}/node_exporter.tar.gz

- name: Get pinned node_exporter release from s3 artifacts bucket
  amazon.aws.s3_object:
    bucket: "{{ artifacts_bucket_name }}"
    object: "thirdparty/prometheus/node_exporter/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.{{ nodeexporter_arch
      }}.tar.gz"
    dest: /home/{{ prometheus_system_user }}/node_exporter.tar.gz
    mode: get
    overwrite: different

- name: Decompress node_exporter installation package
  ansible.builtin.unarchive:
    src: /home/{{ prometheus_system_user }}/node_exporter.tar.gz
    dest: /home/{{ prometheus_system_user }}/bin
    extra_opts: ["--wildcards", "--strip-components=1", "--show-stored-names"]
    include: "*/node_exporter"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_user }}"
    mode: "0750"
    creates: /home/{{ prometheus_system_user }}/bin/node_exporter

- name: Remove the node_exporter installation package
  ansible.builtin.file:
    path: /home/{{ prometheus_system_user }}/node_exporter.tar.gz
    state: absent

- name: Create prometheus node_exporter systemd service
  ansible.builtin.template:
    src: /etc/systemd/system/{{ prometheus_node_exporter_systemd_service_name }}.service.j2
    dest: /etc/systemd/system/{{ prometheus_node_exporter_systemd_service_name }}.service
    mode: "0644"
  notify:
    - restart prometheus node_exporter systemd service

- name: Enable prometheus node_exporter systemd service
  ansible.builtin.systemd:
    name: "{{ prometheus_node_exporter_systemd_service_name }}"
    state: started
    enabled: true
    daemon_reload: true

- name: Allow prometheus node_exporter traffic through firewall
  community.general.ufw:
    port: "{{ prometheus_node_exporter_tcp_port }}"
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'

# - name: Get latest cloudflare ebpf_exporter release info from github
#  uri:
#    url: https://api.github.com/repos/cloudflare/ebpf_exporter/releases/latest
#    return_content: yes
#  register: ebpf_exporter_release_info

# - name: Set release tag fact
#  set_fact:
#    ebpf_exporter_release_tag: "{{ ebpf_exporter_release_info.json.tag_name }}"

# - name: Fail if latest release asset not found
#  fail:
#    msg: "No release_tag found in github latest release response"
#  when: ebpf_exporter_release_tag is not defined

# - name: Set filename based on architecture
#  set_fact:
#    ebpf_exporter_asset_url: https://github.com/cloudflare/ebpf_exporter/releases/download/{{ ebpf_exporter_release_tag }}/ebpf_exporter.{{ ansible_architecture }}

- name: Create ebpf_exporter /opt directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0750"
    state: directory
  loop:
    - "{{ ebpf_exporter_base_directory }}"
    - "{{ ebpf_exporter_base_directory }}/bin"
    - "{{ ebpf_exporter_base_directory }}/modules"

# - name: Download the latest cloudflare ebpf_exporter release from github
#  get_url:
#    url: "{{ ebpf_exporter_asset_url }}"
#    dest: "{{ ebpf_exporter_base_directory }}/bin/ebpf_exporter"
#    owner: root
#    group: root
#    mode: 0750

- name: Get pinned ebpf_exporter release from s3 artifacts bucket
  amazon.aws.s3_object:
    bucket: "{{ artifacts_bucket_name }}"
    object: "thirdparty/cloudflare/ebpf_exporter/{{ ebpf_exporter_version }}/ebpf_exporter.{{ ansible_architecture }}"
    dest: "{{ ebpf_exporter_base_directory }}/bin/ebpf_exporter"
    mode: get
    overwrite: different

- name: Ensure ebpf_exporter binary is executable
  ansible.builtin.file:
    path: "{{ ebpf_exporter_base_directory }}/bin/ebpf_exporter"
    owner: root
    group: root
    mode: "0750"

- name: Copy custom ebpf modules and configs
  ansible.builtin.copy:
    src: /ebpf_exporter/modules/{{ ansible_architecture }}/
    dest: "{{ ebpf_exporter_base_directory }}/modules/"
    owner: root
    group: root
    mode: "0640"

- name: Create ebpf_exporter systemd service
  ansible.builtin.template:
    src: /etc/systemd/system/{{ ebpf_exporter_systemd_service_name }}.service.j2
    dest: /etc/systemd/system/{{ ebpf_exporter_systemd_service_name }}.service
    mode: "0644"
  notify:
    - restart ebpf_exporter systemd service

- name: Enable prometheus ebpf_exporter systemd service
  ansible.builtin.systemd:
    name: "{{ ebpf_exporter_systemd_service_name }}"
    state: started
    enabled: true
    daemon_reload: true

- name: Allow ebpf_exporter traffic through firewall
  community.general.ufw:
    port: "{{ ebpf_exporter_tcp_port }}"
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'
