---
- name: Apply sysctl values
  ansible.builtin.command: sysctl --system
- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart wireguard
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: true
    daemon_reload: true
