---
- name: Apply sysctl values
  shell: sysctl --system

- name: Reload nftables
  systemd:
    name: nftables
    state: restarted
    enabled: true
    daemon_reload: yes

- name: Restart wireguard
  systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: true
    daemon_reload: yes
