- name: Apply sysctl values
  shell: sysctl --system

- name: Reload nftables
  systemd:
    name: nftables
    state: restarted
    daemon_reload: yes

- name: Restart wireguard
  systemd:
    name: wireguard
    state: restarted
    daemon_reload: yes
