---
- name: Restart spire service
  ansible.builtin.systemd:
    name: "{{ spire_server_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Update system CA certificates
  ansible.builtin.command:
    cmd: update-ca-certificates
  changed_when: true
