modules:

  # http GET checks
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: []
      fail_if_ssl: false
      fail_if_not_ssl: false
      preferred_ip_protocol: "ip4"

  # http GET checks with tls required and a valid cert
  http_2xx_strict_tls:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: []
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"

  # http GET checks with tls required and any cert
  http_2xx_insecure_tls:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: []
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"

  # http POST checks
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      valid_status_codes: []
      preferred_ip_protocol: "ip4"

  # grpc plaintext checks
  grpc_plain:
    prober: grpc
    timeout: 5s
    grpc:
      tls: false
      preferred_ip_protocol: "ip4"

  # grpc checks with tls required and a valid cert
  grpc_strict_tls:
    prober: grpc
    timeout: 5s
    grpc:
      tls: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"

  # grpc checks with tls required and any cert
  grpc_insecure_tls:
    prober: grpc
    timeout: 5s
    grpc:
      tls: true
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"

  # icmp check
  icmp:
    prober: icmp
    timeout: 3s
    icmp:
      preferred_ip_protocol: "ip4"

  # tcp connect check
  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"

  # dns query results check
  dns:
    prober: dns
    timeout: 5s
    dns:
      query_name: "grafana.use2.obs.phxi.net"
      query_type: "A"
      preferred_ip_protocol: "ip4"
