---
 - name: prometheus playbook
   hosts: all
   become: true
   handlers:
     - import_tasks: ../handlers/main.yml
   vars_files:
     - ../vars/default.yml
     - ../vars/{{ ansible_os_family }}.yml

   tasks:
     - name: Get instance metadata
       ec2_metadata_facts:

     - name: Print all environment vars for debugging
       debug:
         var: hostvars[inventory_hostname]
         verbosity: 2

     #- name: Ensure required variables are defined
     #  fail:
     #    msg: "{{ item }} must be defined use -e {{ item }}=value"
     #  when: (lookup('vars', item, default=None)) is none
     #  loop:
     #    - env

     - name: Get latest Prometheus release info from github
       uri:
         url: https://api.github.com/repos/prometheus/prometheus/releases/latest
         return_content: yes
       register: prometheus_release_info

     - name: Set release tag fact
       set_fact:
         prometheus_release_tag: "{{ prometheus_release_info.json.tag_name }}"

     - name: Set filename based on architecture
       set_fact:
         prometheus_filename: >-
           {%- if ansible_architecture == "aarch64" -%}
           linux-arm64.tar.gz
           {%- else -%}
           linux-amd64.tar.gz
           {%- endif -%}

     - name: Find {{ ansible_architecture }} asset URL from release assets
       set_fact:
         prometheus_asset_url: "{{ item.browser_download_url }}"
       loop: "{{ prometheus_release_info.json.assets }}"
       when: "prometheus_filename in item.name"

     - name: Fail if {{ ansible_architecture }} asset not found
       fail:
         msg: "No {{ ansible_architecture }} asset found github latest release response."
       when: prometheus_asset_url is not defined

     - name: Create prometheus user
       user:
         name: "{{ prometheus_system_user }}"
         password: '*'
         umask: 0027
         shell: /usr/sbin/nologin
         system: true

     - name: Download the latest Prometheus ({{ prometheus_release_tag }}) linux-amd64 release from github ({{ prometheus_asset_url }})
       get_url:
         url: "{{ prometheus_asset_url }}"
         dest: /home/{{ prometheus_system_user }}/prometheus3.tar.gz

     - name: Create prometheus bin, conf, data, scrapedata directories
       file:
         path: /home/{{ prometheus_system_user }}/{{ item }}
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
         mode: 0750
         state: directory
       loop:
         - bin
         - bin/sd
         - conf
         - conf/rules
         - conf/rules/server
         - conf/scrape.d/
         - conf/scrape.d/apps
         - conf/scrape.d/infra
         - conf/scrape.d/blackbox
         - conf/file_sd.d/
         - conf/file_sd.d/blackbox-http
         - data
         - scrapedata

     - name: Decompress prometheus installation package
       unarchive:
         src: /home/{{ prometheus_system_user }}/prometheus3.tar.gz
         dest: /home/{{ prometheus_system_user }}/bin
         extra_opts: ['--wildcards', '--strip-components=1','--show-stored-names']
         include: ["*/prometheus", "*/promtool"]
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
         mode: 0750
         creates: /home/{{ prometheus_system_user }}/bin/prometheus

     - name: Remove the prometheus installation package
       file:
         path: /home/{{ prometheus_system_user }}/prometheus3.tar.gz
         state: absent

     - name: Modify prometheus main configuration
       template:
         src: ../templates/prometheus/conf/prometheus.yml.j2
         dest: /home/{{ prometheus_system_user }}/conf/prometheus.yml
         mode: 0644
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
       notify: restart prometheus service

     - name: Create prometheus infra scrape target configurations
       template:
         src: ../templates/prometheus/conf/scrape.d/infra/{{ item }}.yml.j2
         dest: /home/{{ prometheus_system_user }}/conf/scrape.d/infra/{{ item }}.yml
         mode: 0644
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
       notify: restart prometheus service
       loop:
         - aws-sd-infra
         - aws-sd-ebpf

     - name: Create blackbox_exporter scrape job configurations
       template:
         src: ../templates/prometheus/conf/scrape.d/blackbox/{{ item }}.yml.j2
         dest: /home/{{ prometheus_system_user }}/conf/scrape.d/blackbox/{{ item }}.yml
         mode: 0644
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
       notify: restart prometheus service
       loop:
         - blackbox-http

     - name: Create blackbox_exporter file_sd target configurations
       template:
         src: ../templates/prometheus/conf/file_sd.d/blackbox-http/{{ item }}.yml.j2
         dest: /home/{{ prometheus_system_user }}/conf/file_sd.d/blackbox-http/{{ item }}.yml
         mode: 0644
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
       notify: restart prometheus service
       loop:
         - alertmanager
         - grafana
         - loki
         - mimir
         - pyroscope
         - tempo

     - name: Create alerting and recording rule configurations
       template:
         src: ../templates/prometheus/conf/rules/}}.yml.j2
         dest: /home/{{ prometheus_system_user }}/conf/rules/server/{{ item }}.yml
         mode: 0644
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
       notify: restart prometheus service
       loop:
         - server

     - name: Copy alerting and recording rules
       copy:
         src: ../files/prometheus/conf/rules/{{ item }}
         dest: /home/{{ prometheus_system_user }}/conf/rules/{{ item }}
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
         mode: 0640
       notify: restart prometheus service
       loop:
         - server

     #- name: Create prometheus apps scrape target configurations
     #  template:
     #    src: ../templates/prometheus/conf/scrape.d/apps/{{ item }}.yml.j2
     #    dest: /home/{{ prometheus_system_user }}/conf/scrape.d/apps/{{ item }}.yml
     #    mode: 0644
     #    owner: "{{ prometheus_system_user }}"
     #    group: "{{ prometheus_system_user }}"
     #  notify: restart prometheus service
     #  when: ansible_os_family == 'Debian'
     #  loop:
     #    - alertmanager
     #    - grafana
     #    - mimir
     #    - monitoring-etcd
     #    - memcached-mimir
     #    - memcached-loki
     #    - prometheus

     - name: Create prometheus systemd service
       template:
         src: ../templates/etc/systemd/system/{{ prometheus_systemd_service_name }}.service.j2
         dest: /etc/systemd/system/{{ prometheus_systemd_service_name }}.service
         mode: 0644
       notify: restart prometheus service

     - name: Allow prometheus traffic through firewall
       ufw:
         port: "{{ prometheus_tcp_port }}"
         proto: tcp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

     - name: Tune some sysctl parameters for networking
       sysctl:
         name: "{{ item.name }}"
         state: present
         value: "{{ item.value }}"
         sysctl_file: /etc/sysctl.conf
       loop:
        - { name: net.ipv4.icmp_ratelimit, value: 0 }
        - { name: net.ipv4.icmp_msgs_burst, value: 0 }
        - { name: net.ipv4.icmp_msgs_per_sec, value: 0 }
        - { name: net.ipv4.icmp_ratemask, value: 0 }
        - { name: net.core.rmem_max, value: 26214400 }
        - { name: net.core.wmem_max, value: 26214400 }
        - { name: net.core.rmem_default, value: 26214400 }
        - { name: net.core.wmem_default, value: 26214400 }
        - { name: net.core.netdev_max_backlog, value: 5000 }

     - name: Get latest prometheus blackbox_exporter release info from github
       uri:
         url: https://api.github.com/repos/prometheus/blackbox_exporter/releases/latest
         return_content: yes
       register: latest_release_info

     - name: Set blackbox_exporter release tag fact
       set_fact:
         latest_release_tag: "{{ latest_release_info.json.tag_name }}"

     - name: Check if a newer blackbox_exporter version exists than the pinned version
       ansible.builtin.debug:
         msg: |
           #################################################################
           # WARNING: New blackbox_exporter version available              #
           #   Pinned: {{ blackbox_exporter_version }}                     #
           #   Latest: {{ latest_release_tag }}                            #
           #################################################################
       when: latest_release_tag[1:] is version(blackbox_exporter_version, '>')
       run_once: true
       changed_when: false

     - name: Set filename based on architecture
       set_fact:
         asset_url: >-
           {%- if ansible_architecture == "aarch64" -%}
           https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-arm64.tar.gz
           {%- else -%}
           https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz
           {%- endif -%}

     - name: Download the pinned blackbox_exporter release ({{ blackbox_exporter_version }}) from github ({{ asset_url }})
       get_url:
         url: "{{ asset_url }}"
         dest: /home/{{ prometheus_system_user }}/blackbox_exporter.zip

     - name: Decompress blackbox_exporter installation package
       unarchive:
         src: /home/{{ prometheus_system_user }}/blackbox_exporter.zip
         dest: /home/{{ prometheus_system_user }}/bin
         #extra_opts: ['--strip-components=1','--show-stored-names']
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
         mode: 0750
         creates: /home/{{ prometheus_system_user }}/bin/blackbox_exporter

     - name: Remove the blackbox_exporter installation package
       file:
         path: /home/{{ prometheus_system_user }}/blackbox_exporter.zip
         state: absent

     - name: Modify blackbox_exporter main configuration
       template:
         src: ../templates/blackbox_exporter/conf/blackbox.yml.j2
         dest: /home/{{ prometheus_system_user }}/conf/blackbox.yml
         mode: 0644
         owner: "{{ prometheus_system_user }}"
         group: "{{ prometheus_system_user }}"
       notify: restart blackbox_exporter service

     - name: Create blackbox_exporter systemd service
       template:
         src: ../templates/etc/systemd/system/{{ blackbox_exporter_systemd_service_name }}.service.j2
         dest: /etc/systemd/system/{{ blackbox_exporter_systemd_service_name }}.service
         mode: 0644
       notify: restart blackbox_exporter service
