---
osquery_package_name: osquery
# osquery_package_version: 5.22.1-1.linux
osquery_systemd_service_name: osquery
osquery_system_user: osquery
osquery_config_base_path: "/etc"
osquery_packs_path: /opt/osquery/share/osquery/packs/
