---
-
- name: Include OS variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

- name: Print all variables for debugging
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 2

- name: Configure sysctl settings to allow forwarding
  ansible.builtin.template:
    src: ../templates/etc/sysctl.d/999-phxi-nat.conf.j2
    dest: /etc/sysctl.d/999-phxi-nat.conf
  notify: Apply sysctl values

- name: Find wan interface from default route
  ansible.builtin.set_fact:
    wan_if: >-
      {{ ansible_default_ipv4.interface
          | default(ansible_facts.default_ipv4.interface, true)
          | default(ansible_default_ipv6.interface, true) }}

- name: Configure nftables to allow forwarding
  ansible.builtin.template:
    src: ../templates/etc/nftables.conf.j2
    dest: /etc/nftables.conf
  notify: Reload nftables
