---
 - name: mimir playbook
   hosts: all
   become: true
   vars_files:
     - ../vars/default.yml
     - ../vars/{{ ansible_os_family }}.yml
   vars:
     mimir_role: "{{ lookup('env', 'MIMIRROLE') }}"

   tasks:
     - name: Get instance metadata
       ec2_metadata_facts:

     - name: Print all environment vars for debugging
       debug:
         var: hostvars[inventory_hostname]
         verbosity: 2

     - name: Exit with failure if no mimir role is defined
       fail:
         msg: No ansible roles found in ENV var MIMIRROLE (expected one of 'distributor', 'ingester', 'query-frontend', 'querier', 'query-scheduler', 'store-gateway', 'compactor')
       when: mimir_role not in ['distributor', 'ingester', 'query-frontend', 'querier', 'query-scheduler', 'store-gateway', 'compactor']

     - name: Ensure required variables are defined
       fail:
         msg: "{{ item }} must be defined use -e {{ item }}=value"
       when: (lookup('vars', item, default=None)) is none
       with_items:
         - env
         - mimir_role

     - name: Create mimir user
       user:
         name: "{{ mimir_system_user }}"
         password: '*'
         umask: 0027
         shell: /usr/sbin/nologin
         system: true

     - name: Create mimir bin, conf, data directories
       file:
         path: /home/{{ mimir_system_user }}/{{ item }}
         owner: "{{ mimir_system_user }}"
         group: "{{ mimir_system_user }}"
         mode: 0750
         state: directory
       loop:
         - bin
         - conf
         - conf/ssl
         - data

     - name: Generate private key for local self signed ssl cert
       community.crypto.openssl_privatekey:
         path: /home/{{ mimir_system_user }}/conf/ssl/cert.key
         owner: "{{ mimir_system_user }}"

     - name: Generate CSR for self-signed certificate for local https listener
       community.crypto.openssl_csr_pipe:
         privatekey_path: /home/{{ mimir_system_user }}/conf/ssl/cert.key
         common_name: "{{ ansible_nodename }}"
       register: csr

     - name: Generate self-signed certificate for local https listener
       community.crypto.x509_certificate:
         path: /home/{{ mimir_system_user }}/conf/ssl/cert.pem
         csr_content: "{{ csr.csr }}"
         privatekey_path: /home/{{ mimir_system_user }}/conf/ssl/cert.key
         owner: "{{ mimir_system_user }}"
         provider: selfsigned

     - name: Check if mimir is already installed
       stat:
         path: /home/{{ mimir_system_user }}/bin/mimir
       register: mimir_binary

     - name: Get latest mimir release info from github
       uri:
         url: https://api.github.com/repos/grafana/mimir/releases/latest
         return_content: yes
       register: release_info
       when: not mimir_binary.stat.exists

     - name: Set release tag fact
       set_fact:
         release_tag: "{{ release_info.json.tag_name }}"
       when: not mimir_binary.stat.exists

     - name: Set filename based on architecture
       set_fact:
         mimir_arch: >-
           {%- if ansible_architecture == "aarch64" -%}
           mimir-linux-arm64
           {%- else -%}
           mimir-linux-amd64
           {%- endif -%}
       when: not mimir_binary.stat.exists

     - name: Find asset URL from release assets based on architecture
       set_fact:
         asset_url: "{{ (release_info.json.assets | selectattr('name', 'equalto', mimir_arch) | map(attribute='browser_download_url') | first) }}"
       when: not mimir_binary.stat.exists

     - name: Fail if asset not found for our architecture
       fail:
         msg: "No asset found github latest release response matching our architecture {{ ansible_architecture }}"
       when: asset_url is not defined and not mimir_binary.stat.exists

     - name: Download the latest mimir release from github
       get_url:
         url: "{{ asset_url }}"
         dest: /home/{{ mimir_system_user }}/bin/mimir
         owner: "{{ mimir_system_user }}"
         group: "{{ mimir_system_user }}"
         mode: 0750
       when: not mimir_binary.stat.exists

     - name: Create mimir systemd service
       template:
         src: ../templates/etc/systemd/system/mimir.service.j2
         dest: /etc/systemd/system/{{ mimir_systemd_service_name[mimir_role] }}.service
         mode: 0644

     - name: Modify mimir main configuration
       template:
         #src: ../templates/mimir/conf/{{ mimir_role }}.yml.j2
         src: ../templates/mimir/conf/mimir.yml.j2
         dest: /home/{{ mimir_system_user }}/conf/mimir.yml
         mode: 0640
         owner: "{{ mimir_system_user }}"
         group: "{{ mimir_system_user }}"
       notify: restart mimir service
       when: ansible_os_family == 'Debian'

     - name: Allow mimir http traffic through firewall
       ufw:
         port: "{{ mimir_http_tcp_port }}"
         proto: tcp
         rule: allow
       # this is used both for service traffic in case of distributors and query-frontend, and for prometheus metrics scraping on all services
       #when: ansible_distribution == 'Ubuntu' and (mimir_role == 'distributor' or mimir_role == 'query-frontend')
       when: ansible_distribution == 'Ubuntu'

     - name: Allow mimir grpc traffic through firewall
       ufw:
         port: "{{ mimir_grpc_tcp_port }}"
         proto: tcp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

     - name: Allow mimir cluster memberlist tcp traffic through firewall
       ufw:
         port: "{{ mimir_cluster_memberlist_port }}"
         proto: tcp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

     - name: Allow mimir cluster memberlist udp traffic through firewall
       ufw:
         port: "{{ mimir_cluster_memberlist_port }}"
         proto: udp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

   handlers:
     - name: restart mimir service
       systemd:
         name: "{{ mimir_systemd_service_name[mimir_role] }}"
         state: restarted
         enabled: true
         daemon_reload: true
