---
 - name: alloy playbook
   hosts: all
   become: true
   vars_files:
     - ../vars/default.yml
     - ../vars/{{ ansible_os_family }}.yml

   tasks:
     - name: Get instance metadata
       ec2_metadata_facts:

     - name: Print all environment vars for debugging
       debug:
         var: hostvars[inventory_hostname]
         verbosity: 2

     - name: Set facts from environment variables
       set_fact:
         service_name: "{{ ansible_env.SERVICENAME | default('unknown') }}"
         service_component: "{{ ansible_env.SERVICECOMPONENT | default(ansible_env.SERVICENAME | default('unknown')) }}"
         project: "{{ ansible_env.PROJECT | default('unknown') }}"
         namespace: "{{ ansible_env.NAMESPACE | default('unknown') }}"

     - name: Ensure required variables are defined
       fail:
         msg: "{{ item }} must be defined use -e {{ item }}=value or set the associated ENV var"
       when: vars[item] is not defined or vars[item] is none
       with_items:
         - platform_env
         - service_name
         - service_component
         - project
         - namespace
         - hostname_no_instanceid

     - name: Set variable for hostname without instanceid used to correlate metric, logs, traces, profiles, etc
       set_fact:
         hostname_no_instanceid: "{{ ansible_hostname.split('-')[0:-1] | join('-') }}"

     # 12/1/25 - this is all in common now to prevent deploy time failures involving apt conflicts since all nodes need this
     # - name: Stop ssm to prevent apt conflicts on fresh box patching
     #   command:
     #     cmd: systemctl stop snap.amazon-ssm-agent.amazon-ssm-agent

     # - name: Install dependency packages
     #   package:
     #     name: "{{ item }}"
     #     state: present
     #   with_items:
     #     - apt-transport-https
     #     - software-properties-common
     #     - wget

     # - name: Install the grafana gpg key
     #   shell:
     #     cmd: wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /usr/share/keyrings/grafana-archive-keyring.gpg
     #     creates: /usr/share/keyrings/grafana-archive-keyring.gpg

     # - name: Ensure grafana gpg key is 644 not 640 or apt breaks
     #   file:
     #     path: /usr/share/keyrings/grafana-archive-keyring.gpg
     #     mode: 0644
     #     owner: root
     #     group: root

     # - name: Add the grafana apt repository
     #   apt_repository:
     #     repo: 'deb [signed-by=/usr/share/keyrings/grafana-archive-keyring.gpg] https://apt.grafana.com stable main'
     #     state: present
     #     filename: grafana
     #     # causing apt locks somehow
     #     #update_cache: true
     #     update_cache: false

     # - name: Update apt cache after adding repo
     #   apt:
     #     update_cache: yes
     #   register: apt_update
     #   until: apt_update is succeeded
     #   retries: 10
     #   delay: 6

     # - name: Install alloy package
     #   package:
     #     name: alloy
     #     state: present

     # - name: Start ssm service
     #   command:
     #    cmd: systemctl start snap.amazon-ssm-agent.amazon-ssm-agent

     - name: Modify alloy main configuration
       template:
         src: ../templates/etc/alloy/config.alloy.j2
         dest: /etc/alloy/config.alloy
         mode: 0644
         owner: root
         group: alloy
       notify: restart alloy service
       when: ansible_os_family == 'Debian'

     - name: Modify alloy service configuration
       ini_file:
         path: /usr/lib/systemd/system/alloy.service
         section: Service
         option: "{{ item.option }}"
         value: "{{ item.value }}"
         no_extra_spaces: true
       loop:
         - { option: "User", value: "root" }
         - { option: "Group", value: "root" }
       notify: restart alloy service
       when: ansible_os_family == 'Debian'

     - name: Enable alloy systemd service
       systemd:
         name: "{{ alloy_systemd_service_name }}"
         state: started
         enabled: true
         daemon_reload: true

   handlers:
     - name: restart alloy service
       systemd:
         name: "{{ alloy_systemd_service_name }}"
         state: restarted
         enabled: true
         daemon_reload: true
