---
- name: Restart prometheus node_exporter systemd service
  ansible.builtin.systemd:
    name: "{{ prometheus_node_exporter_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart ebpf_exporter systemd service
  ansible.builtin.systemd:
    name: "{{ ebpf_exporter_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
