- name: restart prometheus node_exporter systemd service
  systemd:
    name: "{{ prometheus_node_exporter_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: yes

- name: restart ebpf_exporter systemd service
  systemd:
    name: "{{ ebpf_exporter_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: yes
