---
- name: Include OS variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

- name: Get instance metadata
  amazon.aws.ec2_metadata_facts:

- name: Set facts from ssm here since they require ec2 metadata to lookup region
  ansible.builtin.set_fact:
    account_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/account/name', region=ansible_ec2_instance_identity_document_region) }}"
    artifacts_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/artifacts/bucket/name', region=ansible_ec2_instance_identity_document_region) }}"
    company_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/company/name', region=ansible_ec2_instance_identity_document_region) }}"
    env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region) }}"
    hosted_zone_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/dns/hosted_zone/name', region=ansible_ec2_instance_identity_document_region) }}"
    platform_env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region) }}"
    alerts_push_endpoints: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/alerts/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    metrics_push_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/metrics/push/endpoint', region=ansible_ec2_instance_identity_document_region) }}"
    tempo_s3_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/app/tempo/s3/bucket/name', region=ansible_ec2_instance_identity_document_region) }}"

- name: Set facts from environment variables
  ansible.builtin.set_fact:
    service_name: "{{ ansible_env.SERVICENAME | default('unknown') }}"
    service_component: "{{ ansible_env.SERVICECOMPONENT | default(ansible_env.SERVICENAME | default('unknown')) }}"
    project: "{{ ansible_env.PROJECT | default('unknown') }}"
    namespace: "{{ ansible_env.NAMESPACE | default('unknown') }}"
    tempo_role: "{{ lookup('env', 'TEMPOROLE') }}"

- name: Print all environment vars for debugging
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 2

- name: Exit with failure if no tempo role is defined
  ansible.builtin.fail:
    msg: No ansible roles found in ENV var TEMPOROLE (expected one of 'compactor', 'distributor', 'ingester', 'metrics-generator', 'query-frontend', 'querier')
  when: tempo_role not in ['compactor', 'distributor', 'ingester', 'metrics-generator', 'query-frontend', 'querier']

- name: Ensure required variables are defined
  ansible.builtin.fail:
    msg: "{{ item }} must be defined use -e {{ item }}=value"
  when: (lookup('vars', item, default=None)) is none
  loop:
    - env
    - tempo_role

- name: Create tempo user
  ansible.builtin.user:
    name: "{{ tempo_system_user }}"
    password: "*"
    umask: "027"
    shell: /usr/sbin/nologin
    system: true

- name: Create tempo bin, conf, data directories
  ansible.builtin.file:
    path: /home/{{ tempo_system_user }}/{{ item }}
    owner: "{{ tempo_system_user }}"
    group: "{{ tempo_system_user }}"
    mode: "0750"
    state: directory
  loop:
    - bin
    - conf
    - conf/ssl
    - data
    - data/metrics
    - data/traces

- name: Check if ssl cert already exists
  ansible.builtin.stat:
    path: /home/{{ tempo_system_user }}/conf/ssl/cert.pem
  register: tempo_cert

- name: Generate private key for local self signed ssl cert
  community.crypto.openssl_privatekey:
    path: /home/{{ tempo_system_user }}/conf/ssl/cert.key
    owner: "{{ tempo_system_user }}"
  when: not tempo_cert.stat.exists

- name: Generate CSR for self-signed certificate for local https listener
  community.crypto.openssl_csr_pipe:
    privatekey_path: /home/{{ tempo_system_user }}/conf/ssl/cert.key
    common_name: "{{ ansible_nodename }}"
  register: csr
  when: not tempo_cert.stat.exists

- name: Generate self-signed certificate for local https listener
  community.crypto.x509_certificate:
    path: /home/{{ tempo_system_user }}/conf/ssl/cert.pem
    csr_content: "{{ csr.csr }}"
    privatekey_path: /home/{{ tempo_system_user }}/conf/ssl/cert.key
    owner: "{{ tempo_system_user }}"
    provider: selfsigned
  when: not tempo_cert.stat.exists

- name: Check if tempo is already installed
  ansible.builtin.stat:
    path: /home/{{ tempo_system_user }}/bin/tempo
  register: tempo_binary

# - name: Get latest tempo release info from github
#  uri:
#    url: https://api.github.com/repos/grafana/tempo/releases/latest
#    return_content: yes
#  register: release_info
#  when: not tempo_binary.stat.exists

# - name: Set release tag fact
#  set_fact:
#    release_tag: "{{ release_info.json.tag_name[1:] }}"
#  when: not tempo_binary.stat.exists

# - name: Set filename based on architecture
#  set_fact:
#    tempo_arch: >-
#      {%- if ansible_architecture == "aarch64" -%}
#      tempo_{{ release_tag }}_linux_arm64.tar.gz
#      {%- else -%}
#      tempo_{{ release_tag }}_linux_amd64.tar.gz
#      {%- endif -%}
#  when: not tempo_binary.stat.exists

# - name: Find asset URL from release assets based on architecture
#  set_fact:
#    asset_url: "{{ (release_info.json.assets | selectattr('name', 'equalto', tempo_arch) | map(attribute='browser_download_url') | first) }}"
#  when: not tempo_binary.stat.exists

# - name: Fail if asset not found for our architecture
#  fail:
#    msg: "No asset found github latest release response matching our architecture {{ ansible_architecture }}"
#  when: asset_url is not defined and not tempo_binary.stat.exists

# - name: Download the latest tempo release from github
#  get_url:
#    url: "{{ asset_url }}"
#    dest: /home/{{ tempo_system_user }}/tempo.zip
#    owner: "{{ tempo_system_user }}"
#    group: "{{ tempo_system_user }}"
#    mode: 0750
#  when: not tempo_binary.stat.exists

- name: Set normalized architecture fact
  ansible.builtin.set_fact:
    arch_normalized: >-
      {%- if ansible_architecture == "aarch64" -%} arm64{%- else -%} amd64{%- endif -%}

- name: Get pinned Tempo release from s3 artifacts bucket
  amazon.aws.s3_object:
    bucket: "{{ artifacts_bucket_name }}"
    object: "thirdparty/grafana/tempo/v{{ tempo_version }}/tempo_{{ tempo_version }}_linux_{{ arch_normalized }}.tar.gz"
    dest: /home/{{ tempo_system_user }}/tempo.tar.gz
    mode: get
    overwrite: different

- name: Decompress tempo installation package
  ansible.builtin.unarchive:
    src: /home/{{ tempo_system_user }}/tempo.tar.gz
    dest: /home/{{ tempo_system_user }}/bin
    # extra_opts: ['--strip-components=1','--show-stored-names']
    owner: "{{ tempo_system_user }}"
    group: "{{ tempo_system_user }}"
    mode: "0750"
    creates: /home/{{ tempo_system_user }}/bin/tempo

- name: Remove the tempo installation package
  ansible.builtin.file:
    path: /home/{{ tempo_system_user }}/tempo.tar.gz
    state: absent

- name: Create tempo systemd service
  ansible.builtin.template:
    src: /etc/systemd/system/tempo.service.j2
    dest: /etc/systemd/system/{{ tempo_systemd_service_name[tempo_role] }}.service
    mode: "0644"

- name: Modify tempo main configuration
  ansible.builtin.template:
    src: /tempo/conf/tempo.yml.j2
    dest: /home/{{ tempo_system_user }}/conf/tempo.yml
    mode: "0640"
    owner: "{{ tempo_system_user }}"
    group: "{{ tempo_system_user }}"
  notify: Restart tempo service
  when: ansible_os_family == 'Debian'

- name: Allow tempo http traffic through firewall
  community.general.ufw:
    port: "{{ tempo_http_tcp_port }}"
    proto: tcp
    rule: allow
  # this is used both for service traffic in case of distributors and query-frontend, and for prometheus metrics scraping on all services
  # when: ansible_distribution == 'Ubuntu' and (tempo_role == 'distributor' or tempo_role == 'query-frontend')
  when: ansible_distribution == 'Ubuntu'

- name: Allow tempo grpc traffic through firewall
  community.general.ufw:
    port: "{{ tempo_grpc_tcp_port }}"
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'

- name: Allow tempo otlp grpc traffic through firewall
  community.general.ufw:
    port: "{{ tempo_otlp_grpc_tcp_port }}"
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'

- name: Allow tempo otlp http traffic through firewall
  community.general.ufw:
    port: "{{ tempo_otlp_http_tcp_port }}"
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'

- name: Allow tempo cluster memberlist tcp traffic through firewall
  community.general.ufw:
    port: "{{ tempo_cluster_memberlist_port }}"
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'

- name: Allow tempo cluster memberlist udp traffic through firewall
  community.general.ufw:
    port: "{{ tempo_cluster_memberlist_port }}"
    proto: udp
    rule: allow
  when: ansible_distribution == 'Ubuntu'
