---
spire_version: 1.14.2
spire_binary_sha256: ce3ef08470ac914f2cc834a3c90e94b7a49e7be166f33a868bd171bee4bb10d1

spire_ca_ttl: 72h
spire_ca_key_type: ec-p384
spire_ca_subject_country: US
spire_ca_subject_organization:
  - linnemanlabs.com
spire_ca_subject_common_name: Linneman Labs Root CA
spire_db_host: spire-rds.chog2qu22cu2.us-east-2.rds.amazonaws.com
spire_db_port: 5432
spire_db_name: spire
spire_db_user: spire_server
spire_agent_svid_ttl: 1h
spire_default_svid_ttl: 1h
spire_intermediate_cert_arn: arn:aws:secretsmanager:us-east-2:283209027407:secret:app/spire/server/intermediate/cert-wbHUYE
spire_intermediate_key_arn: arn:aws:secretsmanager:us-east-2:283209027407:secret:app/spire/server/intermediate/key-av1Icr 
spire_intermediate_bundle_arn: arn:aws:secretsmanager:us-east-2:283209027407:secret:app/spire/server/intermediate/bundle-MohJOG
spire_log_level: INFO
spire_log_format: json
spire_log_audit_enabled: true
spire_server_address: 0.0.0.0
spire_server_grpc_port: 8081
spire_server_systemd_service_name: spire-server
spire_server_system_user: spire
#spire_trust_domain:
spire_trust_materials_bucket_param: /platform/trust/s3/bucket/name
spire_trust_materials_cert_chain_path: certs/spire-ca-chain.pem
#spire_signer_type: kms
