---
- name: Restart etcd service
  ansible.builtin.systemd:
    name: "{{ etcd_systemd_service_name }}"
    state: restarted
    enabled: true
  # etcd errors out when if a replacement instance is launched, etcd expects the hostname assigned to its node to resolve to its own ip,
  # and exits when it resolves to a different ip. dns is set after ansible playbooks run to ensure the server is healthy first. have to
  # just let systemd restart the service for a minute until dns is updated
    daemon_reload: true
  ignore_errors: true

- name: Reload systemd daemon configurations
  ansible.builtin.systemd:
    daemon_reload: true
