---
 - name: loki playbook
   hosts: all
   become: true
   vars_files:
     - ../vars/default.yml
     - ../vars/{{ ansible_os_family }}.yml
   vars:
     loki_role: "{{ lookup('env', 'LOKIROLE') }}"

   pre_tasks:
     - name: Get instance metadata
       ec2_metadata_facts:

     - name: Set facts from ssm here since they require ec2 metadata to lookup region
       set_fact: 
         account_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/account/name', region=ansible_ec2_instance_identity_document_region ) }}"
         artifacts_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/artifacts/bucket/name', region=ansible_ec2_instance_identity_document_region ) }}"
         company_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/company/name', region=ansible_ec2_instance_identity_document_region ) }}"
         env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region ) }}"
         hosted_zone_name: "{{ lookup('amazon.aws.aws_ssm', '/platform/dns/hosted_zone/name', region=ansible_ec2_instance_identity_document_region ) }}"
         platform_env: "{{ lookup('amazon.aws.aws_ssm', '/platform/env/name', region=ansible_ec2_instance_identity_document_region ) }}"
         alerts_push_endpoints: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/alerts/push/endpoint', region=ansible_ec2_instance_identity_document_region ) }}"
         metrics_push_endpoint: "{{ lookup('amazon.aws.aws_ssm', '/platform/obs/metrics/push/endpoint', region=ansible_ec2_instance_identity_document_region ) }}"
         loki_s3_bucket_name: "{{ lookup('amazon.aws.aws_ssm', '/app/loki/s3/bucket/name', region=ansible_ec2_instance_identity_document_region ) }}"

     - name: Set facts from environment variables
       set_fact:
         service_name: "{{ ansible_env.SERVICENAME | default('unknown') }}"
         service_component: "{{ ansible_env.SERVICECOMPONENT | default(ansible_env.SERVICENAME | default('unknown')) }}"
         project: "{{ ansible_env.PROJECT | default('unknown') }}"
         namespace: "{{ ansible_env.NAMESPACE | default('unknown') }}"

     - name: Print all environment vars for debugging
       debug:
         var: hostvars[inventory_hostname]
         verbosity: 2

     - name: Exit with failure if no loki role is defined
       fail:
         msg: No ansible roles found in ENV var LOKIROLE (expected one of 'distributor', 'ingester', 'query-frontend', 'querier', 'query-scheduler', 'index-gateway', 'compactor', 'ruler')
       when: loki_role not in ['distributor', 'ingester', 'query-frontend', 'querier', 'query-scheduler', 'index-gateway', 'compactor', 'ruler']

     - name: Ensure required variables are defined
       fail:
         msg: "{{ item }} must be defined use -e {{ item }}=value"
       when: (lookup('vars', item, default=None)) is none
       with_items:
         - env
         - loki_role
   tasks:
     - name: Create loki user
       user:
         name: "{{ loki_system_user }}"
         password: '*'
         umask: 0027
         shell: /usr/sbin/nologin
         system: true

     - name: Create loki bin, conf, data directories
       file:
         path: /home/{{ loki_system_user }}/{{ item }}
         owner: "{{ loki_system_user }}"
         group: "{{ loki_system_user }}"
         mode: 0750
         state: directory
       loop:
         - bin
         - conf
         - conf/rules
         - conf/ssl
         - data
         - data/chunks
         - data/index
         - data/index_cache
         - data/compactor

     - name: Generate private key for local self signed ssl cert
       community.crypto.openssl_privatekey:
         path: /home/{{ loki_system_user }}/conf/ssl/cert.key
         owner: "{{ loki_system_user }}"

     - name: Generate CSR for self-signed certificate for local https listener
       community.crypto.openssl_csr_pipe:
         privatekey_path: /home/{{ loki_system_user }}/conf/ssl/cert.key
         common_name: "{{ ansible_nodename }}"
       register: csr

     - name: Generate self-signed certificate for local https listener
       community.crypto.x509_certificate:
         path: /home/{{ loki_system_user }}/conf/ssl/cert.pem
         csr_content: "{{ csr.csr }}"
         privatekey_path: /home/{{ loki_system_user }}/conf/ssl/cert.key
         owner: "{{ loki_system_user }}"
         provider: selfsigned

# running into github api rate limits. moving this to a central system using sbom soon
#     - name: Get latest Loki release info from github
#       uri:
#         url: https://api.github.com/repos/grafana/loki/releases/latest
#         return_content: yes
#       register: latest_release_info

#     - name: Set release tag fact
#       set_fact:
#         latest_release_tag: "{{ latest_release_info.json.tag_name }}"

#     - name: Warn if a newer Loki version exists
#       ansible.builtin.debug:
#         msg: |
#           #################################################################
#           # WARNING: New Loki version available                           #
#           #   Pinned: {{ loki_version }}                                  #
#           #   Latest: {{ latest_release_tag }}                           #
#           #################################################################
#       when: latest_release_tag[1:] is version(loki_version, '>')
#       run_once: true
#       changed_when: false

#     - name: Get pinned Loki release info from github
#       uri:
#         url: https://github.com/grafana/loki/releases/tag/v{{ loki_version }}
#         return_content: yes
#       register: release_info

     - name: Set filename based on architecture
       set_fact:
         loki_filename: >-
           {%- if ansible_architecture == "aarch64" -%}
           loki-linux-arm64.zip
           {%- else -%}
           loki-linux-amd64.zip
           {%- endif -%}

#     - name: Find asset URL from release assets based on architecture
#       set_fact:
#         asset_url: "{{ item.browser_download_url }}"
#       loop: "{{ release_info.json.assets }}"
#       when: "loki_filename in item.name"

#     - name: Fail if asset not found for our architecture
#       fail:
#         msg: "No asset found github latest release response matching our architecture {{ ansible_architecture }}"
#       when: asset_url is not defined

#     - name: Download the pinned Loki release ({{ loki_version }}) from github ({{ asset_url }})
#       get_url:
#         url: https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-arm64.zip
#         dest: /home/{{ loki_system_user }}/loki.zip


     - name: Get pinned Loki release from s3 artifacts bucket 
       amazon.aws.s3_object:
         bucket: "{{ artifacts_bucket_name }}"
         object: "thirdparty/grafana/loki/v{{ loki_version }}/{{ loki_filename }}"
         dest: /home/{{ loki_system_user }}/loki.zip
         mode: get
         overwrite: different
       
     - name: Decompress loki installation package
       unarchive:
         src: /home/{{ loki_system_user }}/loki.zip
         dest: /home/{{ loki_system_user }}/bin
         #extra_opts: ['--strip-components=1','--show-stored-names']
         owner: "{{ loki_system_user }}"
         group: "{{ loki_system_user }}"
         mode: 0750
         creates: /home/{{ loki_system_user }}/bin/loki

     - name: Remove the loki installation package
       file:
         path: /home/{{ loki_system_user }}/loki.zip
         state: absent

     - name: Create loki systemd service
       template:
         src: ../templates/etc/systemd/system/loki.service.j2
         dest: /etc/systemd/system/{{ loki_systemd_service_name[loki_role] }}.service
         mode: 0644

     - name: Modify loki main configuration
       template:
         src: ../templates/loki/conf/loki.yml.j2
         dest: /home/{{ loki_system_user }}/conf/loki.yml
         mode: 0644
       when: ansible_os_family == 'Debian'
       notify: restart loki service

     - name: Enable {{ loki_systemd_service_name[loki_role] }} systemd service
       service:
         name: "{{ loki_systemd_service_name[loki_role] }}"
         state: started
         enabled: true

     - name: Allow loki http traffic through firewall
       ufw:
         port: "{{ loki_http_tcp_port }}"
         proto: tcp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

     - name: Allow loki grpc traffic through firewall
       ufw:
         port: "{{ loki_grpc_tcp_port }}"
         proto: tcp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

     - name: Allow loki cluster memberlist tcp traffic through firewall
       ufw:
         port: "{{ loki_cluster_memberlist_tcp_port }}"
         proto: tcp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

     - name: Allow loki cluster memberlist udp traffic through firewall
       ufw:
         port: "{{ loki_cluster_memberlist_udp_port }}"
         proto: udp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

   handlers:
     - name: restart loki service
       systemd:
         name: "{{ loki_systemd_service_name[loki_role] }}"
         state: restarted
         enabled: true
         daemon_reload: true
