---
- name: Restart linnemanlabs-trust-portal server service
  ansible.builtin.systemd:
    name: "{{ trustportal_systemd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
