---
 - name: sitesuper-web playbook
   hosts: all
   become: true
   vars_files:
     - ../vars/default.yml
     - ../vars/{{ ansible_os_family }}.yml

   tasks:
     - name: Get instance metadata
       ec2_metadata_facts:

     - name: Print all environment vars for debugging
       debug:
         var: hostvars[inventory_hostname]
         verbosity: 2

     - name: Ensure required variables are defined
       fail:
         msg: "{{ item }} must be defined use -e {{ item }}=value"
       when: (lookup('vars', item, default=None)) is none
       loop:
         - env

     - name: Create sitesuper-web user
       user:
         name: "{{ sitesuper_web_system_user }}"
         password: '*'
         umask: 0027
         shell: /usr/sbin/nologin
         system: true

     - name: Create sitesuper directories
       file:
         path: /home/{{ sitesuper_web_system_user }}/{{ item }}
         owner: "{{ sitesuper_web_system_user }}"
         group: "{{ sitesuper_web_system_user }}"
         mode: 0750
         state: directory
       loop:
         - bin
         - log

     - name: Set architecture format based on normalized naming
       set_fact:
         architecture_normalized_name: >-
           {%- if ansible_architecture == "aarch64" -%}
           arm64
           {%- else -%}
           amd64
           {%- endif -%}

     - name: Temporarily bail out early
       ansible.builtin.meta: end_play

     - name: Get sitesuper-web release from s3
       amazon.aws.s3_object:
         bucket: "{{ artifacts_bucket_name }}"
         object: "/apps/sitesuper/web/releases/v{{ sitesuper_version }}/linux/{{ architecture_normalized_name }}/sitesuper-web"
         dest: /home/{{ sitesuper_web_system_user }}/bin/sitesuper-web
         mode: get
         overwrite: different

     - name: Create sitesuper-web systemd service
       template:
         src: ../templates/etc/systemd/system/{{ sitesuper_web_systemd_service_name }}.service.j2
         dest: /etc/systemd/system/{{ sitesuper_web_systemd_service_name }}.service
         mode: 0644
       notify: restart sitesuper-web service

     - name: Enable sitesuper-web systemd service
       systemd:
         name: "{{ sitesuper_web_systemd_service_name }}"
         state: started
         enabled: true
         daemon_reload: true

     - name: Allow sitesuper-web traffic through firewall
       ufw:
         port: "{{ sitesuper_web_tcp_port }}"
         proto: tcp
         rule: allow
       when: ansible_distribution == 'Ubuntu'

   handlers:
     - name: restart sitesuper-web service
       systemd:
         name: "{{ sitesuper_web_systemd_service_name }}"
         state: restarted
         enabled: true
         daemon_reload: true
