---
pyroscope_system_user: pyroscope
pyroscope_systemd_service_name:
  distributor: pyroscope-distributor
  ingester: pyroscope-ingester
  query-frontend: pyroscope-query-frontend
  querier: pyroscope-querier
  query-scheduler: pyroscope-query-scheduler
  store-gateway: pyroscope-store-gateway
  compactor: pyroscope-compactor
